name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
      
    steps:
      - name: Delete package
        uses: NamrataJha/delete-package-versions@b213b92f86f164d781f6a3d735d79f34abe6e657
        with: 
            owner: NamrataJha
            repo: actions-test-3
            package-name: actions-test
            min-versions-to-keep: 5
            token: ${{ secrets.PAT }}

 


          
