name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
      
    steps:
      - name: Delete package
        uses: OmarCastro/delete-package-versions@d2531724efdbb55705ba2050c9460c2e87127a0f
        with: 
            owner: NamrataJha
            repo: test-pkg-1
            package-names: '^/[a-z]+-test-[0-9]'
            min-versions-to-keep: 100
            ignore-versions: '^(0|[1-9]\\d*)\\.0\\.0$'

 


          
